apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: audiototext
  janus-idp.io/tekton: audiototext
  backstage.io/kubernetes-id: audiototext
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: audiototext
resources:
  - application-dev.yaml
