apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: audiototext
  janus-idp.io/tekton: audiototext
  backstage.io/kubernetes-id: audiototext
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: audiototext
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
