apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: audiototext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audiototext
  name: audiototext
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
