apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: audiototext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audiototext
  name: audiototext
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: audiototext
    weight: 100
  wildcardPolicy: None
