apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: audiototext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audiototext
  name: audiototext
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: audiototext
